---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-version-test
spec:
  selector:
    matchLabels:
      app: nginx-version-test
  template:
    metadata:
      labels:
        app: nginx-version-test
    spec:
      containers:
      - name: nginx
        image: nginx:version
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-vt-svc
spec:
  selector:
    app: nginx-version-test
  ports:
  - port: 80
    targetPort: 80
