apiVersion: apps/v1
kind: Deployment
metadata:
  name: top10sports
spec:
  selector:
    matchLabels:
      app: top10sports
  template:
    metadata:
      labels:
        app: top10sports
    spec:
      containers:
      - name: top10sports-container
        image: sujoysarkar087/top10sports
        #        resources:
        #          limits:
        #            memory: "128Mi"
        #            cpu: "200m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: top10sports-svc
spec:
  type: NodePort
  selector:
    app: top10sports
  ports:
  - port: 80
    targetPort: 80
